- name: install and run nginx
  hosts: web
  become: yes
  tasks:
  - name: install nginx package
    ansible.bulitin.package:
      name: nginx
      state: present
  - name: run nginx
    ansible.builtin.package:
      name: nginx
      state: started
