- name: conditions
  hosts: localhost
  become: yes
  tasks:
  - name: check roboshopuser exit or not
    ansible.builtin.command: id roboshop
    register: username
    ignore_errors: true
  - name: print variable value
    ansible.builtin.debug:
      msg: "user output {{username}}"
  - name: print exitcode or returncode
    ansible.builtin.debug:
      msg: "status is {{username.rc}}"
  - name: create username
    ansible.builtin.user:
      name: roboshop
    when: username.rc !=0