- name: installing packages
  hosts: localhost
  become: yes
  tasks:
  - name: print package
    ansible.builtin.packages:
      name: "{{item}}"
      state:  present
    loop:
    - git
    - mysql
    - postfix